<?php

/**
 * BooksCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BooksCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BooksCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BooksCategory');
    }
}