<?php

/**
 * NewsTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsTags');
    }
}