generator:
  class: sfDoctrineGenerator
  param:
    model_class:           news
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        body: {rich: true}
      list:
        display: [body, _imagen, brief, Category, _tags]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
