generator:
  class: sfDoctrineGenerator
  param:
    model_class:           book
    theme:                 mpReality
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          book
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, _author, _category]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
